from django.core.exceptions import ValidationError
import re

def validate_name(name):
    pass

def validate_descrip(descrip):
    pass