from django.core.exceptions import ValidationError
import re

def validate_curr_char(curr_char):
    pass